# Generated by Django 6.1 on 2026-08-30 17:43

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=events.models.event_image_upload_path),
        ),
    ]
