# Generated by Django 6.1 on 2026-08-31 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_name',
        ),
        migrations.AddField(
            model_name='event',
            name='street_address',
            field=models.CharField(blank=True, default='', help_text='Street and house number', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, default='', help_text='Postal/Zip code', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='maps_url',
            field=models.URLField(blank=True, default='', help_text='Google Maps link (optional)'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Select city', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='events.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Select country', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.country'),
        ),
    ]
