# Generated by Django 6.1 on 2026-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_city_country_remove_event_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, default='', help_text='Link to ticket page or external event site'),
        ),
    ]
