# Generated by Django 6.1 on 2026-09-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Visible to public only when approved by admin.'),
        ),
    ]
