# Generated by Django 6.1 on 2026-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventimage_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pending_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
