# Generated by Django 6.1 on 2026-09-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_pending_description_event_pending_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been edited'),
        ),
        migrations.AddField(
            model_name='event',
            name='edit_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Edit link expires 7 days after creation', null=True),
        ),
    ]
