# Generated by Django 6.1 on 2026-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_edit_count_event_edit_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If checked, this event will always appear at the top of the list.'),
        ),
    ]
