# Generated by Django 6.1 on 2026-09-07 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_city_alter_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pending_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_events', to='events.city'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_events', to='events.country'),
        ),
    ]
