# Generated by Django 6.1 on 2026-09-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_pending_city_alter_event_pending_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pending_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='pending_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
